### ISSUE TITLE
自带的反连平台报错无法使用

### ISSUE THREAD

**Issue by tcwy2016** [w-digital-scanner/w13scan#443]
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/60C89E21C89DF60E/tools/webtools/xray/w13scan/W13SCAN/lib/reverse/reverse_dns.py", line 158, in dns_start
    dns_server.start()
  File "/mnt/60C89E21C89DF60E/tools/webtools/xray/w13scan/W13SCAN/lib/reverse/reverse_dns.py", line 152, in start
    dns_udp_server = SocketServer.UDPServer((host, port), DnsRequestHandler)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

[10:28:14] [INFO] User KeyboardInterrupt

**Comment by boy-hack** [comment]
Address already in use
