### ISSUE TITLE
无法成功运行（python3 w13scan.py -s 127.0.0.1:7778 --html）这条命令

### ISSUE THREAD

**Issue by XiongYN** [w-digital-scanner/w13scan#526]
[04:35:36] [INFO] HTTPServer is running at address('127.0.0.1','7778')......
Traceback (most recent call last):
  File "D:\渗透工具\w13scan-master\W13SCAN\w13scan.py", line 93, in <module>
    main()
  File "D:\渗透工具\w13scan-master\W13SCAN\w13scan.py", line 80, in main
    baseproxy = AsyncMitmProxy(server_addr=conf.server_addr, https=True)
  File "D:\渗透工具\w13scan-master\W13SCAN\lib\proxy\baseproxy.py", line 697, in __init__
    self.ca = CAAuth(ca_file="ca.pem", cert_file='ca.crt')
  File "D:\渗透工具\w13scan-master\W13SCAN\lib\proxy\baseproxy.py", line 323, in __init__
    self._gen_ca()  # 生成CA证书，需要添加到浏览器的合法证书机构中
  File "D:\渗透工具\w13scan-master\W13SCAN\lib\proxy\baseproxy.py", line 342, in _gen_ca
    self.cert.gmtime_adj_notBefore(0)
  File "D:\python3\lib\site-packages\OpenSSL\crypto.py", line 1346, in gmtime_adj_notBefore
    notBefore = _lib.X509_get_notBefore(self._x509)
AttributeError: module 'lib' has no attribute 'X509_get_notBefore'

**Comment by Mick-code** [comment]
I solved it through this method：
```
# pip uninstall pyOpenSSL
# pip install pyOpenSSL
```
